services:
  nyx_mysql:
    image: mysql:8.0.37
    container_name: nyx_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456QWE
    volumes:
      - ./volume/mysql/data:/var/lib/mysql
    networks:
      - nyx_network

  nyx_air:
    image: cosmtrek/air
    container_name: nyx_air
    restart: always
    ports:
      - 8000:8000
    environment:
      - air_wd=/go/src/github.com/cosmtrek/hub
    volumes:
      - ./:/go/src/github.com/cosmtrek/hub
    working_dir: /go/src/github.com/cosmtrek/hub
    command: ["-c", ".air.toml"]
    networks:
      - nyx_network

networks:
  nyx_network:
    driver: bridge
    name: nyx_network
