services:
  nyx_mysql:
    image: mysql:8.0.37
    container_name: nyx_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456QWE
    volumes:
      - ./volume/mysql/data:/var/lib/mysql
    networks:
      - nyx_network

  redis:
    image: redis:8.0.2
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volume/redis/data:/data
    command: redis-server --requirepass a%UE4kVbs8b$

networks:
  nyx_network:
    driver: bridge
    name: nyx_network
